#!/bin/sh

# Initial Mac Setup
echo "Installing developer software"

# install xcode
Xcode-select —install

# install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# install cask
brew install cask

#install textmate
brew install --cask textmate

# Install iterm2
brew install --cask iterm2

#install VS Code
brew install --cask visual-studio-code

#install git
brew install git

# install asdf dependencies
brew install coreutils curl

# install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0

# initialize asdf
. "$HOME/.asdf/asdf.sh"

# add nodejs plugin to asdf
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

# install nodejs latest
asdf install nodejs latest
asdf global nodejs latest
# install pnpm
npm install -g pnpm

# Install dotfiles
cwd=`pwd`
BACKUP_DIR=$HOME/.backup
echo "Checking $BACKUP_DIR directory"
while [ -d $BACKUP_DIR ]
do
  BACKUP_DIR="$BACKUP_DIR"_"$RANDOM"
  echo "the backup folder already exists trying $BACKUP_DIR instead"
done

mkdir $BACKUP_DIR

echo "backing up existing dot files."
for each in `ls -lad \.* | grep ^- | rev | cut -w -f 1 | rev`
do
  if [ -f ~/$each ]; then
    mv ~/$each $BACKUP_DIR/$each
  fi
  ln -s ${cwd}/$each ${HOME}/${each}
done

echo "Do you wish to remove all dotfiles backed up in the $BACKUP_DIR directory?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -frd $BACKUP_DIR; break;;
        No ) break;;
    esac
done